package com.vitalsense.app.core.ui.theme

import androidx.compose.runtime.Composable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.runtime.staticCompositionLocalOf

/**
 * Supported application languages.
 * Display name and native script name are provided for high-accessibility selection.
 */
enum class AppLanguage(val code: String, val displayName: String, val nativeName: String, val buttonLabel: String) {
    ENGLISH("en", "English", "English", "EN"),
    HINDI("hi", "Hindi", "हिन्दी", "हिन्दी"),
    TAMIL("ta", "Tamil", "தமிழ்", "தமிழ்"),
    MARATHI("mr", "Marathi", "मराठी", "मराठी")
}

data class AppStrings(
    val appName: String,
    val tagline: String,
    val online: String,
    val offline: String,
    val exit: String,
    val cancel: String,
    val done: String,
    val save: String,
    val submit: String,
    val urgent: String,
    val active: String,
    val highPriority: String,
    val highRisk: String,
    val moderateRisk: String,
    val lowRisk: String,

    // Roles
    val rolePatient: String,
    val rolePatientDesc: String,
    val roleAsha: String,
    val roleAshaDesc: String,
    val roleDoctor: String,
    val roleDoctorDesc: String,
    val roleAdmin: String,
    val roleAdminDesc: String,

    // Login Screen
    val whoIsUsing: String,
    val selectRoleDesc: String,
    val patientSignIn: String,
    val ashaSignIn: String,
    val doctorSignIn: String,
    val adminSignIn: String,
    val mobileNumber: String,
    val ashaHelperIdOptional: String,
    val uniqueAshaId: String,
    val securityPin: String,
    val doctorEmail: String,
    val password: String,
    val adminPasscode: String,
    val logInAsPatient: String,
    val logInAsAsha: String,
    val logInAsDoctor: String,
    val logInAsAdmin: String,
    val quickDemoLogin: String,
    val offlineBanner: String,

    // Top Bar
    val patientPortal: String,
    val ashaPortal: String,
    val doctorPortal: String,
    val adminPortal: String,
    val actingAsProxy: String,
    val exitProxy: String,

    // Patient Home
    val namaste: String,
    val village: String,
    val ashaAssigned: String,
    val patientGuideTitle: String,
    val patientGuideMsg: String,
    val offlineHealthCard: String,
    val viewCard: String,
    val activeCondition: String,
    val nextCheckup: String,
    val noneScheduled: String,
    val cachedOffline: String,
    val howCanWeHelp: String,
    val tapServiceDesc: String,
    val myPrescriptions: String,
    val uploadRx: String,
    val noPrescriptions: String,
    val scanOrWrite: String,
    val districtAdvisories: String,
    val issuedBy: String,
    val emergencySos: String,
    val emergencySosDesc: String,
    val trigger: String,
    val confirmSosTitle: String,
    val confirmSosMsg: String,
    val yesSendAlert: String,
    val sosDispatchedTitle: String,
    val sosDispatchedMsg: String,
    val zeroInternetFallbacks: String,
    val smsAsha: String,
    val call108: String,

    // Categories
    val catGeneralMedicine: String,
    val catMaternalHealth: String,
    val catFitness: String,
    val catNutrition: String,
    val catMentalHealth: String,
    val catEmergency: String,

    // ASHA Home
    val assignedVillages: String,
    val uniqueAshaCardTitle: String,
    val shareAshaIdDesc: String,
    val newPatient: String,
    val sendNotice: String,
    val villageCaseload: String,
    val noPatientsYet: String,
    val scanRx: String,
    val proxyMode: String,
    val emergencyPatientAlerts: String,
    val sosAlertForPatient: String,
    val confirmSosPatientMsg: String,
    val sosDispatchedForPatient: String,
    val sosFailedForPatient: String,
    val retry: String,

    // Doctor Home & Case Detail
    val pendingCases: String,
    val criticalCases: String,
    val scheduledAppts: String,
    val activeInQueue: String,
    val specialistQueue: String,
    val noPendingCases: String,
    val symptoms: String,
    val review: String,
    val history: String,
    val upcomingConsultations: String,
    val proposeAppt: String,
    val dispensaryStock: String,
    val lowStock: String,
    val patientDirectory: String,
    val searchPatient: String,
    val searchPlaceholder: String,
    val caseQueue: String,
    val reportedSymptoms: String,
    val doctorAdviceTitle: String,
    val quickTemplates: String,
    val issueRx: String,
    val refer: String,
    val submitAdvice: String,
    val updateAdvice: String,

    // Admin Home
    val districtCommand: String,
    val surveillanceRegion: String,
    val totalActiveCases: String,
    val monitoredVillages: String,
    val outbreakSurveillance: String,
    val liveTelemetry: String,
    val broadcastAlertBtn: String,
    val dispatchedDirectives: String,
    val dispensaryInventory: String,

    // Prescription & OCR
    val uploadPrescriptionTitle: String,
    val cameraAiScan: String,
    val writeDown: String,
    val onDeviceAiBadge: String,
    val selectDocSample: String,
    val extractedRawText: String,
    val parsedMedicines: String,
    val saveDigitizedRx: String,
    val addMedicine: String,
    val medicineName: String,
    val dosage: String,
    val duration: String,
    val frequency: String,
    val savePrescriptionRecord: String,

    // Calling & Teleconsultation
    val callRinging: String,
    val callConnecting: String,
    val callOngoing: String,
    val callEnded: String,
    val endCall: String,
    val mute: String,
    val unmute: String,
    val speaker: String,
    val videoCall: String,
    val voiceCall: String,
    val emergencyDoctorCall: String,
    val routineConsultCall: String,
    val autoEscalatingInSeconds: String,
    val emergencyDoctorOnCall: String,

    // Medicine Availability & Nearby Stores
    val medicineAvailabilityTitle: String,
    val nearbyPharmaciesTitle: String,
    val inStock: String,
    val outOfStock: String,
    val limitedStock: String,
    val alternativesAvailable: String,
    val findNearbyStores: String,
    val openInMaps: String,

    // Specialist Referrals
    val doctorReferralsTitle: String,
    val referToSpecialistTitle: String,
    val chooseSpecialty: String,
    val urgencyLevel: String,
    val clinicalQuestionTitle: String,
    val reasonForReferral: String,
    val attachRecords: String,
    val acceptReferral: String,
    val declineReferral: String,
    val requestMoreInfo: String,
    val specialistFindingsTitle: String,
    val specialistRecommendationsTitle: String,
    val submitSpecialistFindings: String,
    val referralSentSuccess: String,
    val referralCompleted: String,
    val awaitingSpecialistReview: String,
    val specialistAccepted: String,
    val specialistDeclined: String,

    // Language Dialog
    val selectLanguageTitle: String,
    val selectLanguageSubtitle: String,
    val currentLanguageBadge: String,
    val applyLanguage: String,

    // Hospital Queue
    val liveQueueTitle: String,
    val tokenNumber: String,
    val callNextPatient: String,
    val startConsultation: String,
    val completeConsultation: String,
    val noShow: String,
    val skipPatient: String,
    val prioritizePatient: String,

    // Doctor Analytics & Medical History
    val triageBreakdownTitle: String,
    val statTotal: String,
    val statPending: String,
    val statResolved: String,
    val statReferred: String,
    val medicalHistoryTitle: String,
    val noMedicalHistory: String,
    val medicalHistoryTab: String
)

val EnglishStrings = AppStrings(
    appName = "VitalSense",
    tagline = "SehatSetu — Rural Health Bridge",
    online = "Online",
    offline = "Offline",
    exit = "Exit",
    cancel = "Cancel",
    done = "Done",
    save = "Save",
    submit = "Submit",
    urgent = "URGENT",
    active = "ACTIVE",
    highPriority = "HIGH PRIORITY",
    highRisk = "High Risk",
    moderateRisk = "Moderate Risk",
    lowRisk = "Low Risk",

    rolePatient = "Patient",
    rolePatientDesc = "Health card & SOS",
    roleAsha = "ASHA Worker",
    roleAshaDesc = "Caseload & Proxy",
    roleDoctor = "Doctor",
    roleDoctorDesc = "Review & Prescribe",
    roleAdmin = "Admin",
    roleAdminDesc = "Outbreak Trends",

    whoIsUsing = "Who is using the app?",
    selectRoleDesc = "Select your role to access your dedicated healthcare portal:",
    patientSignIn = "👤 Patient Sign-In",
    ashaSignIn = "🤝 ASHA Worker Sign-In",
    doctorSignIn = "🩺 Doctor Clinical Portal",
    adminSignIn = "🛡️ District Health Admin",
    mobileNumber = "Mobile Number",
    ashaHelperIdOptional = "ASHA Helper ID (Optional)",
    uniqueAshaId = "Unique ASHA ID",
    securityPin = "4-Digit Security PIN",
    doctorEmail = "Medical Registration / Email",
    password = "Password",
    adminPasscode = "District Admin Passcode",
    logInAsPatient = "Log In as Patient →",
    logInAsAsha = "Log In to ASHA Caseload →",
    logInAsDoctor = "Log In to Clinical Portal →",
    logInAsAdmin = "Enter District Health Command →",
    quickDemoLogin = "⚡ Quick 1-Tap Demo Login:",
    offlineBanner = "📶 Offline-First: Health Card & Core Tools Work With Zero Internet",

    patientPortal = "Patient Portal",
    ashaPortal = "ASHA Worker Caseload",
    doctorPortal = "Clinical Review Portal",
    adminPortal = "District Outbreak Command",
    actingAsProxy = "Acting as Proxy for Patient:",
    exitProxy = "Exit Proxy",

    namaste = "Namaste",
    village = "Village",
    ashaAssigned = "ASHA",
    patientGuideTitle = "Your Rural Health Portal",
    patientGuideMsg = "Tap any health category below to log symptoms, check prescriptions, or connect with your ASHA helper.",
    offlineHealthCard = "OFFLINE HEALTH CARD",
    viewCard = "View Card →",
    activeCondition = "Active Condition:",
    nextCheckup = "Next Checkup:",
    noneScheduled = "None Scheduled",
    cachedOffline = "Cached Offline ✓",
    howCanWeHelp = "How can we help you today?",
    tapServiceDesc = "Tap a service to report health condition or consult a doctor:",
    myPrescriptions = "💊 My Prescriptions",
    uploadRx = "➕ Upload Rx",
    noPrescriptions = "No prescriptions recorded yet",
    scanOrWrite = "Scan paper slip or write down medicines",
    districtAdvisories = "📢 District Health Advisories",
    issuedBy = "Issued by:",
    emergencySos = "EMERGENCY SOS",
    emergencySosDesc = "Instant dispatch to ASHA & 108 Emergency Ambulance",
    trigger = "TRIGGER",
    confirmSosTitle = "Confirm Emergency SOS?",
    confirmSosMsg = "This will immediately notify your assigned ASHA worker and local primary health center with your emergency profile.",
    yesSendAlert = "🚨 YES, SEND EMERGENCY ALERT",
    sosDispatchedTitle = "Emergency Alert Dispatched!",
    sosDispatchedMsg = "ASHA worker and Emergency Response have been alerted. Stay calm and keep phone active.",
    zeroInternetFallbacks = "Zero-Internet Fallbacks (Always Available):",
    smsAsha = "📱 SMS ASHA Worker Directly",
    call108 = "📞 Call 108 Emergency Ambulance",

    catGeneralMedicine = "General Medicine",
    catMaternalHealth = "Maternal Health",
    catFitness = "Fitness & Physical",
    catNutrition = "Nutrition & Diet",
    catMentalHealth = "Mental Wellness",
    catEmergency = "Emergency Help",

    assignedVillages = "Assigned Villages:",
    uniqueAshaCardTitle = "Your Unique ASHA ID Card",
    shareAshaIdDesc = "Share this 8-character ID or QR with patients in your village to link them directly to your proxy care network.",
    newPatient = "➕ New Patient",
    sendNotice = "📢 Send Notice",
    villageCaseload = "Village Health Caseload",
    noPatientsYet = "No patients registered in your caseload yet.",
    scanRx = "Scan Rx",
    proxyMode = "Proxy Mode",
    emergencyPatientAlerts = "🚨 Emergency Patient Alerts",
    sosAlertForPatient = "Trigger Emergency SOS for Patient?",
    confirmSosPatientMsg = "This will flag the patient as CRITICAL in the district emergency queue and prepare an emergency call.",
    sosDispatchedForPatient = "🚨 Emergency SOS dispatched for patient.",
    sosFailedForPatient = "Failed to dispatch SOS. Please call 108 directly.",
    retry = "Retry",

    pendingCases = "Pending Clinical Cases",
    criticalCases = "Critical / Urgent Cases",
    scheduledAppts = "Today's Appointments",
    activeInQueue = "Active In Queue",
    specialistQueue = "Specialist Queue",
    noPendingCases = "No pending patient cases. All caught up!",
    symptoms = "Symptoms",
    review = "Review Case →",
    history = "Clinical History",
    upcomingConsultations = "Upcoming Consultations",
    proposeAppt = "Propose Appointment",
    dispensaryStock = "Dispensary Stock",
    lowStock = "Low Stock Alerts",
    patientDirectory = "Patient Directory",
    searchPatient = "Search Patients",
    searchPlaceholder = "Type patient name or ID...",
    caseQueue = "Patient Case Queue",
    reportedSymptoms = "Reported Symptoms & Notes",
    doctorAdviceTitle = "Doctor Advice & Response",
    quickTemplates = "Quick Clinical Advice Templates",
    issueRx = "💊 Issue Prescription",
    refer = "🩺 Refer to Specialist",
    submitAdvice = "Submit Clinical Advice",
    updateAdvice = "Update Clinical Advice",

    districtCommand = "District Health Command",
    surveillanceRegion = "Monitoring Region: Bageshwar District",
    totalActiveCases = "Total Active Cases",
    monitoredVillages = "Monitored Villages",
    outbreakSurveillance = "Disease Outbreak Heatmap",
    liveTelemetry = "Live Public Health Telemetry",
    broadcastAlertBtn = "📢 Broadcast Health Advisory",
    dispatchedDirectives = "Active Advisories & Directives",
    dispensaryInventory = "Dispensary Stock & Restock Requests",

    uploadPrescriptionTitle = "Digitize Doctor Prescription",
    cameraAiScan = "📷 Camera / AI Scan",
    writeDown = "✍️ Write Down",
    onDeviceAiBadge = "⚡ On-Device AI: Scans paper prescriptions with zero internet.",
    selectDocSample = "Select a document sample:",
    extractedRawText = "Raw Extracted OCR Text:",
    parsedMedicines = "Identified Medicines",
    saveDigitizedRx = "Save Digitized Prescription ✓",
    addMedicine = "➕ Add Prescribed Medicine:",
    medicineName = "Medicine Name",
    dosage = "Dosage (e.g., 500mg)",
    duration = "Duration (e.g., 5 days)",
    frequency = "Frequency (e.g., Twice daily)",
    savePrescriptionRecord = "Save Prescription Record ✓",

    callRinging = "Ringing...",
    callConnecting = "Connecting...",
    callOngoing = "Call Ongoing",
    callEnded = "Call Ended",
    endCall = "End Call",
    mute = "Mute",
    unmute = "Unmute",
    speaker = "Speaker",
    videoCall = "Video Call",
    voiceCall = "Voice Call",
    emergencyDoctorCall = "🚨 Emergency Doctor Call",
    routineConsultCall = "🩺 Consultation Call",
    autoEscalatingInSeconds = "Auto-escalating to next doctor in %d seconds",
    emergencyDoctorOnCall = "On-Call Emergency Physician",

    medicineAvailabilityTitle = "Medicine Availability & Alternatives",
    nearbyPharmaciesTitle = "Nearby Pharmacies & Medical Stores",
    inStock = "In Stock",
    outOfStock = "Out of Stock",
    limitedStock = "Limited Stock",
    alternativesAvailable = "Alternative Available Nearby",
    findNearbyStores = "Find Nearby Stores",
    openInMaps = "Open in Maps",

    doctorReferralsTitle = "Doctor-to-Doctor Referrals",
    referToSpecialistTitle = "Refer to Specialist",
    chooseSpecialty = "Select Target Specialty",
    urgencyLevel = "Clinical Urgency",
    clinicalQuestionTitle = "Specific Clinical Question / Ask",
    reasonForReferral = "Reason for Referral",
    attachRecords = "Attach Relevant Records",
    acceptReferral = "Accept Referral",
    declineReferral = "Decline Referral",
    requestMoreInfo = "Request More Info",
    specialistFindingsTitle = "Diagnostic Findings",
    specialistRecommendationsTitle = "Recommendations for Referring Doctor",
    submitSpecialistFindings = "Submit Closed-Loop Findings",
    referralSentSuccess = "Referral sent to specialist queue.",
    referralCompleted = "Specialist consultation completed.",
    awaitingSpecialistReview = "Awaiting Specialist Review",
    specialistAccepted = "Specialist Consultation Accepted",
    specialistDeclined = "Referral Declined",

    selectLanguageTitle = "Choose Language / भाषा चुनें",
    selectLanguageSubtitle = "Select your preferred language across the entire application:",
    currentLanguageBadge = "Active Language",
    applyLanguage = "Confirm & Apply",

    liveQueueTitle = "Live Clinic Visit Queue",
    tokenNumber = "Token #%d",
    callNextPatient = "Call Next Patient",
    startConsultation = "Start Consultation",
    completeConsultation = "Complete Consultation",
    noShow = "Mark No-Show",
    skipPatient = "Skip",
    prioritizePatient = "Prioritize",

    triageBreakdownTitle = "Triage Severity Breakdown",
    statTotal = "Total",
    statPending = "Pending",
    statResolved = "Resolved",
    statReferred = "Referred",
    medicalHistoryTitle = "Longitudinal Medical History",
    noMedicalHistory = "No medical history recorded.",
    medicalHistoryTab = "Medical History"
)

val HindiStrings = AppStrings(
    appName = "VitalSense",
    tagline = "सेहतसेतु — ग्रामीण स्वास्थ्य नेटवर्क",
    online = "ऑनलाइन",
    offline = "ऑफलाइन",
    exit = "बाहर निकलें",
    cancel = "रद्द करें",
    done = "पूर्ण",
    save = "सहेजें",
    submit = "जमा करें",
    urgent = "अति आवश्यक",
    active = "सक्रिय",
    highPriority = "उच्च प्राथमिकता",
    highRisk = "उच्च जोखिम",
    moderateRisk = "मध्यम जोखिम",
    lowRisk = "सामान्य / कम जोखिम",

    rolePatient = "मरीज़",
    rolePatientDesc = "स्वास्थ्य कार्ड व आपातकालीन SOS",
    roleAsha = "आशा कार्यकर्ता",
    roleAshaDesc = "गाँव स्वास्थ्य रिकॉर्ड व सहायता",
    roleDoctor = "डॉक्टर",
    roleDoctorDesc = "मरीज़ समीक्षा व ई-पर्चे",
    roleAdmin = "प्रशासक",
    roleAdminDesc = "ज़िला बीमारी निगरानी",

    whoIsUsing = "ऐप का उपयोग कौन कर रहा है?",
    selectRoleDesc = "अपने स्वास्थ्य पोर्टल में प्रवेश करने के लिए अपनी भूमिका चुनें:",
    patientSignIn = "👤 मरीज़ लॉगिन",
    ashaSignIn = "🤝 आशा कार्यकर्ता लॉगिन",
    doctorSignIn = "🩺 डॉक्टर क्लिनिकल पोर्टल",
    adminSignIn = "🛡️ ज़िला स्वास्थ्य प्रशासक",
    mobileNumber = "मोबाइल नंबर",
    ashaHelperIdOptional = "आशा कार्यकर्ता आईडी (वैकल्पिक)",
    uniqueAshaId = "विशिष्ट आशा आईडी",
    securityPin = "4-अंकीय सुरक्षा पिन",
    doctorEmail = "पंजीकरण नंबर / ईमेल",
    password = "पासवर्ड",
    adminPasscode = "प्रशासक सुरक्षा पासकोड",
    logInAsPatient = "मरीज़ के रूप में लॉगिन करें →",
    logInAsAsha = "आशा पोर्टल में लॉगिन करें →",
    logInAsDoctor = "डॉक्टर पोर्टल में लॉगिन करें →",
    logInAsAdmin = "ज़िला स्वास्थ्य कमांड में प्रवेश करें →",
    quickDemoLogin = "⚡ त्वरित 1-टैप डेमो लॉगिन:",
    offlineBanner = "📶 ऑफलाइन-फर्स्ट: स्वास्थ्य कार्ड बिना इंटरनेट के भी काम करता है",

    patientPortal = "मरीज़ स्वास्थ्य पोर्टल",
    ashaPortal = "आशा कार्यकर्ता कार्यक्षेत्र",
    doctorPortal = "डॉक्टर क्लिनिकल पोर्टल",
    adminPortal = "ज़िला बीमारी निगरानी कमांड",
    actingAsProxy = "मरीज़ के प्रतिनिधि के रूप में कार्यरत:",
    exitProxy = "प्रतिनिधि मोड से बाहर निकलें",

    namaste = "नमस्ते",
    village = "गाँव",
    ashaAssigned = "आशा",
    patientGuideTitle = "आपका ग्रामीण स्वास्थ्य पोर्टल",
    patientGuideMsg = "लक्षण दर्ज करने, दवा के पर्चे देखने या अपनी आशा कार्यकर्ता से जुड़ने के लिए नीचे किसी भी श्रेणी पर टैप करें।",
    offlineHealthCard = "ऑफलाइन स्वास्थ्य कार्ड",
    viewCard = "कार्ड देखें →",
    activeCondition = "सक्रिय स्वास्थ्य स्थिति:",
    nextCheckup = "अगली जांच:",
    noneScheduled = "कोई निर्धारित नहीं",
    cachedOffline = "ऑफलाइन सुरक्षित ✓",
    howCanWeHelp = "आज हम आपकी क्या मदद कर सकते हैं?",
    tapServiceDesc = "समस्या बताने या डॉक्टर से सलाह लेने के लिए सेवा चुनें:",
    myPrescriptions = "💊 मेरे डॉक्टर के पर्चे",
    uploadRx = "➕ पर्चा जोड़ें",
    noPrescriptions = "अभी कोई पर्चा दर्ज नहीं है",
    scanOrWrite = "पर्ची स्कैन करें या हाथ से लिखें",
    districtAdvisories = "📢 ज़िला स्वास्थ्य परामर्श",
    issuedBy = "द्वारा जारी:",
    emergencySos = "आपातकालीन SOS",
    emergencySosDesc = "आशा कार्यकर्ता व 108 एम्बुलेंस को तत्काल अलर्ट",
    trigger = "अलर्ट भेजें",
    confirmSosTitle = "क्या आपातकालीन SOS भेजना है?",
    confirmSosMsg = "यह तुरंत आपकी आशा कार्यकर्ता और प्राथमिक स्वास्थ्य केंद्र को आपकी स्थिति के साथ अलर्ट भेजेगा।",
    yesSendAlert = "🚨 हाँ, आपातकालीन अलर्ट भेजें",
    sosDispatchedTitle = "आपातकालीन अलर्ट भेज दिया गया!",
    sosDispatchedMsg = "आशा कार्यकर्ता और आपातकालीन दल को सूचित कर दिया गया है। कृपया शांत रहें।",
    zeroInternetFallbacks = "बिना इंटरनेट के आपातकालीन विकल्प:",
    smsAsha = "📱 आशा कार्यकर्ता को सीधे SMS भेजें",
    call108 = "📞 108 एम्बुलेंस को कॉल करें",

    catGeneralMedicine = "सामान्य चिकित्सा",
    catMaternalHealth = "मातृ स्वास्थ्य",
    catFitness = "शारीरिक स्वास्थ्य",
    catNutrition = "पोषण व आहार",
    catMentalHealth = "मानसिक स्वास्थ्य",
    catEmergency = "आपातकालीन सहायता",

    assignedVillages = "आवंटित गाँव:",
    uniqueAshaCardTitle = "आपका विशिष्ट आशा पहचान पत्र",
    shareAshaIdDesc = "गाँव के मरीज़ों को सीधे अपने नेटवर्क से जोड़ने के लिए यह 8-अक्षरों का कोड या QR साझा करें।",
    newPatient = "➕ नया मरीज़",
    sendNotice = "📢 सूचना भेजें",
    villageCaseload = "गाँव स्वास्थ्य रिकॉर्ड सूची",
    noPatientsYet = "अभी आपकी सूची में कोई मरीज़ पंजीकृत नहीं है।",
    scanRx = "पर्चा स्कैन",
    proxyMode = "प्रतिनिधि मोड",
    emergencyPatientAlerts = "🚨 आपातकालीन मरीज़ अलर्ट",
    sosAlertForPatient = "क्या मरीज़ के लिए आपातकालीन SOS भेजना है?",
    confirmSosPatientMsg = "यह ज़िला आपातकालीन कतार में मरीज़ को गंभीर श्रेणी में दर्ज करेगा।",
    sosDispatchedForPatient = "🚨 मरीज़ के लिए आपातकालीन SOS भेज दिया गया।",
    sosFailedForPatient = "SOS नहीं भेजा जा सका। कृपया सीधे 108 पर कॉल करें।",
    retry = "पुनः प्रयास करें",

    pendingCases = "समीक्षा के लिए लंबित मामले",
    criticalCases = "गंभीर / अति आवश्यक मामले",
    scheduledAppts = "आज के परामर्श",
    activeInQueue = "कतार में सक्रिय मरीज़",
    specialistQueue = "विशेषज्ञ कतार",
    noPendingCases = "कोई लंबित मामला नहीं है। सब पूर्ण!",
    symptoms = "लक्षण",
    review = "मामला देखें →",
    history = "मरीज़ का इतिहास",
    upcomingConsultations = "आगामी परामर्श",
    proposeAppt = "परामर्श समय दें",
    dispensaryStock = "दवाखाना स्टॉक",
    lowStock = "दवा की कमी की चेतावनी",
    patientDirectory = "मरीज़ निर्देशिका",
    searchPatient = "मरीज़ खोजें",
    searchPlaceholder = "मरीज़ का नाम या आईडी लिखें...",
    caseQueue = "मरीज़ केस कतार",
    reportedSymptoms = "दर्ज लक्षण व विवरण",
    doctorAdviceTitle = "डॉक्टर की सलाह",
    quickTemplates = "त्वरित चिकित्सकीय सलाह",
    issueRx = "💊 पर्चा लिखें",
    refer = "🩺 विशेषज्ञ को रेफर करें",
    submitAdvice = "सलाह दर्ज करें",
    updateAdvice = "सलाह अपडेट करें",

    districtCommand = "ज़िला स्वास्थ्य कमांड",
    surveillanceRegion = "निगरानी क्षेत्र: बागेश्वर ज़िला",
    totalActiveCases = "कुल सक्रिय मामले",
    monitoredVillages = "निगरानीधीन गाँव",
    outbreakSurveillance = "संक्रामक बीमारी मानचित्र",
    liveTelemetry = "लाइव स्वास्थ्य डेटा",
    broadcastAlertBtn = "📢 स्वास्थ्य परामर्श जारी करें",
    dispatchedDirectives = "जारी किए गए निर्देश व परामर्श",
    dispensaryInventory = "दवाखाना स्टॉक व आपूर्ति अनुरोध",

    uploadPrescriptionTitle = "डॉक्टर के पर्चे को डिजिटल बनाएं",
    cameraAiScan = "📷 कैमरा / AI स्कैन",
    writeDown = "✍️ हाथ से लिखें",
    onDeviceAiBadge = "⚡ ऑन-डिवाइस AI: बिना इंटरनेट के डॉक्टर की पर्ची स्कैन करता है।",
    selectDocSample = "दस्तावेज़ का नमूना चुनें:",
    extractedRawText = "स्कैन किया गया टेक्स्ट:",
    parsedMedicines = "पहचानी गई दवाइयाँ",
    saveDigitizedRx = "डिजिटल नुस्खा सहेजें ✓",
    addMedicine = "➕ निर्धारित दवा जोड़ें:",
    medicineName = "दवा का नाम",
    dosage = "खुराक",
    duration = "अवधि",
    frequency = "कब लें",
    savePrescriptionRecord = "नुस्खा रिकॉर्ड सहेजें ✓",

    callRinging = "घंटी बज रही है...",
    callConnecting = "कॉल जुड़ रही है...",
    callOngoing = "कॉल जारी है",
    callEnded = "कॉल समाप्त",
    endCall = "कॉल काटें",
    mute = "माइक बंद",
    unmute = "माइक चालू",
    speaker = "स्पीकर",
    videoCall = "वीडियो कॉल",
    voiceCall = "ऑडियो कॉल",
    emergencyDoctorCall = "🚨 आपातकालीन डॉक्टर कॉल",
    routineConsultCall = "🩺 नियमित परामर्श कॉल",
    autoEscalatingInSeconds = "%d सेकंड में अगले डॉक्टर को कॉल जाएगी",
    emergencyDoctorOnCall = "ड्यूटी पर आपातकालीन डॉक्टर",

    medicineAvailabilityTitle = "दवा की उपलब्धता व विकल्प",
    nearbyPharmaciesTitle = "नज़दीकी मेडिकल स्टोर व फार्मेसी",
    inStock = "उपलब्ध है",
    outOfStock = "स्टॉक में नहीं",
    limitedStock = "सीमित स्टॉक",
    alternativesAvailable = "समान असर वाली वैकल्पिक दवा पास में उपलब्ध",
    findNearbyStores = "नज़दीकी स्टोर देखें",
    openInMaps = "मानचित्र में देखें",

    doctorReferralsTitle = "डॉक्टर-टू-डॉक्टर विशेषज्ञ परामर्श",
    referToSpecialistTitle = "विशेषज्ञ को रेफर करें",
    chooseSpecialty = "विशेषज्ञ विभाग चुनें",
    urgencyLevel = "आवश्यकता स्तर",
    clinicalQuestionTitle = "विशिष्ट प्रश्न / नैदानिक पूछ",
    reasonForReferral = "रेफर करने का मुख्य कारण",
    attachRecords = "संबंधित रिपोर्ट व पर्चे जोड़ें",
    acceptReferral = "रेफरल स्वीकार करें",
    declineReferral = "रेफरल अस्वीकार करें",
    requestMoreInfo = "और जानकारी मांगें",
    specialistFindingsTitle = "विशेषज्ञ की नैदानिक जांच रिपोर्ट",
    specialistRecommendationsTitle = "प्रारंभिक डॉक्टर के लिए सलाह",
    submitSpecialistFindings = "विशेषज्ञ रिपोर्ट जमा करें",
    referralSentSuccess = "विशेषज्ञ को रेफरल भेज दिया गया।",
    referralCompleted = "विशेषज्ञ परामर्श पूर्ण हुआ।",
    awaitingSpecialistReview = "विशेषज्ञ डॉक्टर की समीक्षा की प्रतीक्षा है",
    specialistAccepted = "विशेषज्ञ डॉक्टर ने परामर्श स्वीकार किया",
    specialistDeclined = "रेफरल अस्वीकार हुआ",

    selectLanguageTitle = "भाषा चुनें / Select Language",
    selectLanguageSubtitle = "पूरी ऐप के लिए अपनी पसंदीदा भाषा चुनें:",
    currentLanguageBadge = "सक्रिय भाषा",
    applyLanguage = "लागू करें ✓",

    liveQueueTitle = "अस्पताल कतार स्थिति",
    tokenNumber = "टोकन #%d",
    callNextPatient = "अगले मरीज़ को बुलाएं",
    startConsultation = "परामर्श शुरू करें",
    completeConsultation = "परामर्श पूरा करें",
    noShow = "अनुपस्थित दर्ज करें",
    skipPatient = "आगे बढ़ें",
    prioritizePatient = "प्राथमिकता दें",

    triageBreakdownTitle = "ट्राइएज गंभीरता विश्लेषण",
    statTotal = "कुल",
    statPending = "लंबित",
    statResolved = "समाधानित",
    statReferred = "रेफर किया",
    medicalHistoryTitle = "रोगी का संपूर्ण चिकित्सा इतिहास",
    noMedicalHistory = "कोई चिकित्सा इतिहास दर्ज नहीं है।",
    medicalHistoryTab = "चिकित्सा इतिहास"
)

val TamilStrings = AppStrings(
    appName = "VitalSense",
    tagline = "SehatSetu — கிராமப்புற சுகாதார பாலம்",
    online = "ஆன்லைன்",
    offline = "ஆஃப்லைன்",
    exit = "வெளியேறு",
    cancel = "ரத்துசெய்",
    done = "முடிந்தது",
    save = "சேமி",
    submit = "சமர்ப்பி",
    urgent = "அவசரம்",
    active = "செயலில்",
    highPriority = "முக்கிய முன்னுரிமை",
    highRisk = "அதிக ஆபத்து",
    moderateRisk = "நடுத்தர ஆபத்து",
    lowRisk = "குறைந்த ஆபத்து / இயல்பு",

    rolePatient = "நோயாளி",
    rolePatientDesc = "சுகாதார அட்டை மற்றும் அவசர SOS",
    roleAsha = "ஆஷா பணியாளர்",
    roleAshaDesc = "சமூக பராமரிப்பு மற்றும் உதவி",
    roleDoctor = "மருத்துவர்",
    roleDoctorDesc = "மருத்துவ ஆய்வு மற்றும் மருந்துகள்",
    roleAdmin = "நிர்வாகி",
    roleAdminDesc = "மாவட்ட நோய் கண்காணிப்பு",

    whoIsUsing = "பயன்படுத்துபவர் யார்?",
    selectRoleDesc = "உங்கள் சுகாதார போர்ட்டலை அணுக உங்கள் பங்கைத் தேர்ந்தெடுக்கவும்:",
    patientSignIn = "👤 நோயாளி உள்நுழைவு",
    ashaSignIn = "🤝 ஆஷா பணியாளர் உள்நுழைவு",
    doctorSignIn = "🩺 மருத்துவர் போர்ட்டல்",
    adminSignIn = "🛡️ மாவட்ட சுகாதார நிர்வாகம்",
    mobileNumber = "மொபைல் எண்",
    ashaHelperIdOptional = "ஆஷா உதவியாளர் ஐடி (விருப்பத்தேர்வு)",
    uniqueAshaId = "தனித்துவமான ஆஷா ஐடி",
    securityPin = "4-இலக்க பாதுகாப்பு பின்",
    doctorEmail = "மருத்துவப் பதிவு / மின்னஞ்சல்",
    password = "கடவுச்சொல்",
    adminPasscode = "மாவட்ட நிர்வாக கடவுச்சொல்",
    logInAsPatient = "நோயாளியாக உள்நுழைக →",
    logInAsAsha = "ஆஷா போர்ட்டலில் உள்நுழைக →",
    logInAsDoctor = "மருத்துவர் போர்ட்டலில் உள்நுழைக →",
    logInAsAdmin = "மாவட்ட சுகாதார கட்டளைக்கு செல்க →",
    quickDemoLogin = "⚡ 1-தட்டு டெமோ உள்நுழைவு:",
    offlineBanner = "📶 ஆஃப்லைன்: இணையம் இல்லாமலும் சுகாதார அட்டை இயங்கும்",

    patientPortal = "நோயாளி சுகாதார போர்டல்",
    ashaPortal = "ஆஷா பணியாளர் போர்டல்",
    doctorPortal = "மருத்துவ ஆய்வு போர்டல்",
    adminPortal = "மாவட்ட நோய் கண்காணிப்பு",
    actingAsProxy = "நோயாளியின் பிரதிநிதியாக:",
    exitProxy = "பிரதிநிதித்துவத்தை முடிக்கவும்",

    namaste = "வணக்கம்",
    village = "கிராமம்",
    ashaAssigned = "ஆஷா பணியாளர்",
    patientGuideTitle = "உங்கள் கிராமப்புற சுகாதார போர்டல்",
    patientGuideMsg = "அறிகுறிகளை பதிவு செய்ய, மருந்துகளைப் பார்க்க அல்லது உங்கள் ஆஷா பணியாளரைத் தொடர்பு கொள்ள கீழே தொடவும்.",
    offlineHealthCard = "ஆஃப்லைன் சுகாதார அட்டை",
    viewCard = "அட்டையைக் காண்க →",
    activeCondition = "தற்போதைய நிலை:",
    nextCheckup = "அடுத்த பரிசோதனை:",
    noneScheduled = "திட்டமிடப்படவில்லை",
    cachedOffline = "ஆஃப்லைனில் பாதுகாக்கப்பட்டது ✓",
    howCanWeHelp = "இன்று நாங்கள் உங்களுக்கு எவ்வாறு உதவலாம்?",
    tapServiceDesc = "மருத்துவ ஆலோசனை பெற சேவையைத் தேர்ந்தெடுக்கவும்:",
    myPrescriptions = "💊 எனது மருந்துச் சீட்டுகள்",
    uploadRx = "➕ மருந்துச் சீட்டு சேர்",
    noPrescriptions = "மருந்துச் சீட்டுகள் எதுவும் பதிவு செய்யப்படவில்லை",
    scanOrWrite = "சீட்டை ஸ்கேன் செய்யவும் அல்லது எழுதவும்",
    districtAdvisories = "📢 மாவட்ட சுகாதார ஆலோசனைகள்",
    issuedBy = "வெளியிட்டவர்:",
    emergencySos = "அவசர SOS",
    emergencySosDesc = "ஆஷா மற்றும் 108 ஆம்புலன்ஸுக்கு உடனடி உதவி அழைப்பு",
    trigger = "அழை",
    confirmSosTitle = "அவசர SOS அனுப்ப வேண்டுமா?",
    confirmSosMsg = "இது உடனடியாக உங்கள் ஆஷா பணியாளர் மற்றும் ஆரம்ப சுகாதார நிலையத்திற்கு உங்கள் விவரங்களுடன் அவசர எச்சரிக்கையை அனுப்பும்.",
    yesSendAlert = "🚨 ஆம், அவசர எச்சரிக்கை அனுப்பு",
    sosDispatchedTitle = "அவசர எச்சரிக்கை அனுப்பப்பட்டது!",
    sosDispatchedMsg = "ஆஷா பணியாளர் மற்றும் அவசர குழுவிற்கு தகவல் தெரிவிக்கப்பட்டுள்ளது. அமைதியாக இருங்கள்.",
    zeroInternetFallbacks = "இணையமற்ற அவசர வழிகள்:",
    smsAsha = "📱 ஆஷா பணியாளருக்கு நேரடியாக SMS செய்க",
    call108 = "📞 108 ஆம்புலன்ஸை அழைக்கவும்",

    catGeneralMedicine = "பொது மருத்துவம்",
    catMaternalHealth = "தாய்மை நலம்",
    catFitness = "உடற்பயிற்சி மற்றும் நலம்",
    catNutrition = "ஊட்டச்சத்து மற்றும் உணவு",
    catMentalHealth = "மன நலம்",
    catEmergency = "அவசர உதவி",

    assignedVillages = "ஒதுக்கப்பட்ட கிராமங்கள்:",
    uniqueAshaCardTitle = "உங்கள் தனித்துவமான ஆஷா அட்டை",
    shareAshaIdDesc = "கிராமப்புற நோயாளிகளை உங்கள் பராமரிப்பு நெட்வொர்க்கில் இணைக்க இந்த 8-இலக்க குறியீட்டைப் பகிரவும்.",
    newPatient = "➕ புதிய நோயாளி",
    sendNotice = "📢 அறிவிப்பு அனுப்பு",
    villageCaseload = "கிராம சுகாதார பட்டியல்",
    noPatientsYet = "இன்னும் நோயாளிகள் பதிவு செய்யப்படவில்லை.",
    scanRx = "மருந்து ஸ்கேன்",
    proxyMode = "பிரதிநிதி முறை",
    emergencyPatientAlerts = "🚨 அவசர நோயாளி எச்சரிக்கைகள்",
    sosAlertForPatient = "நோயாளிக்கு அவசர SOS அனுப்பவா?",
    confirmSosPatientMsg = "இது மாவட்ட அவசர வரிசையில் நோயாளியை தீவிர நிலையில் பதிவு செய்யும்.",
    sosDispatchedForPatient = "🚨 நோயாளிக்கு அவசர எச்சரிக்கை அனுப்பப்பட்டது.",
    sosFailedForPatient = "எச்சரிக்கை அனுப்ப முடியவில்லை. 108-ஐ நேரடியாக அழைக்கவும்.",
    retry = "மீண்டும் முயற்சி",

    pendingCases = "நிலுவையில் உள்ள வழக்குகள்",
    criticalCases = "அவசர மற்றும் தீவிர வழக்குகள்",
    scheduledAppts = "இன்றைய ஆலோசனைகள்",
    activeInQueue = "வரிசையில் உள்ளவர்கள்",
    specialistQueue = "நிபுணர் வரிசை",
    noPendingCases = "நிலுவை வழக்குகள் ஏதுமில்லை!",
    symptoms = "அறிகுறிகள்",
    review = "ஆய்வு செய் →",
    history = "மருத்துவ வரலாறு",
    upcomingConsultations = "வரவிருக்கும் ஆலோசனைகள்",
    proposeAppt = "நேரம் ஒதுக்கு",
    dispensaryStock = "மருந்தக இருப்பு",
    lowStock = "குறைந்த இருப்பு எச்சரிக்கை",
    patientDirectory = "நோயாளி விபரம்",
    searchPatient = "நோயாளியைத் தேடு",
    searchPlaceholder = "பெயர் அல்லது ஐடியை உள்ளிடவும்...",
    caseQueue = "நோயாளி வரிசை",
    reportedSymptoms = "அறிவிக்கப்பட்ட அறிகுறிகள்",
    doctorAdviceTitle = "மருத்துவர் ஆலோசனை",
    quickTemplates = "விரைவு மருத்துவ ஆலோசனைகள்",
    issueRx = "💊 மருந்துச் சீட்டு வழங்கு",
    refer = "🩺 நிபுணரிடம் பரிந்துரை செய்",
    submitAdvice = "ஆலோசனையை பதிவு செய்",
    updateAdvice = "ஆலோசனையை புதுப்பி",

    districtCommand = "மாவட்ட சுகாதார கட்டளை மையம்",
    surveillanceRegion = "கண்காணிப்பு பகுதி: பாகேஷ்வர் மாவட்டம்",
    totalActiveCases = "மொத்த தீவிர வழக்குகள்",
    monitoredVillages = "கண்காணிக்கப்படும் கிராமங்கள்",
    outbreakSurveillance = "நோய் பரவல் வரைபடம்",
    liveTelemetry = "நேரலை சுகாதார தரவு",
    broadcastAlertBtn = "📢 சுகாதார எச்சரிக்கை வெளியிடு",
    dispatchedDirectives = "செயலில் உள்ள வழிகாட்டுதல்கள்",
    dispensaryInventory = "மருந்தக இருப்பு மற்றும் கோரிக்கைகள்",

    uploadPrescriptionTitle = "மருந்துச் சீட்டை டிஜிட்டல் மயமாக்கு",
    cameraAiScan = "📷 கேமரா / AI ஸ்கேன்",
    writeDown = "✍️ கையேடு மூலம் எழுது",
    onDeviceAiBadge = "⚡ AI ஸ்கேனர்: இணையம் இல்லாமல் காகித மருந்துச் சீட்டைப் படிக்கிறது.",
    selectDocSample = "மாதிரி ஆவணத்தைத் தேர்ந்தெடுக்கவும்:",
    extractedRawText = "ஸ்கேன் செய்யப்பட்ட உரை:",
    parsedMedicines = "கண்டறியப்பட்ட மருந்துகள்",
    saveDigitizedRx = "டிஜிட்டல் மருந்துச் சீட்டைச் சேமி ✓",
    addMedicine = "➕ பரிந்துரைக்கப்பட்ட மருந்தைச் சேர்:",
    medicineName = "மருந்தின் பெயர்",
    dosage = "அளவு (Dosage)",
    duration = "கால அளவு",
    frequency = "எப்போது உட்கொள்ள வேண்டும்",
    savePrescriptionRecord = "மருந்துப் பதிவைச் சேமி ✓",

    callRinging = "ஒலிக்கிறது...",
    callConnecting = "இணைக்கிறது...",
    callOngoing = "அழைப்பு தொடர்கிறது",
    callEnded = "அழைப்பு முடிந்தது",
    endCall = "அழைப்பை முடி",
    mute = "ஒலியை நிறுத்து",
    unmute = "ஒலியை இயக்கு",
    speaker = "ஸ்பீக்கர்",
    videoCall = "வீடியோ அழைப்பு",
    voiceCall = "குரல் அழைப்பு",
    emergencyDoctorCall = "🚨 அவசர மருத்துவர் அழைப்பு",
    routineConsultCall = "🩺 வழக்கமான ஆலோசனை அழைப்பு",
    autoEscalatingInSeconds = "%d வினாடிகளில் அடுத்த மருத்துவருக்கு மாற்றப்படும்",
    emergencyDoctorOnCall = "பணியில் உள்ள அவசர மருத்துவர்",

    medicineAvailabilityTitle = "மருந்து இருப்பு மற்றும் மாற்றுகள்",
    nearbyPharmaciesTitle = "அருகிலுள்ள மருந்தகங்கள்",
    inStock = "இருப்பில் உள்ளது",
    outOfStock = "இருப்பில் இல்லை",
    limitedStock = "குறைந்த அளவு இருப்பு",
    alternativesAvailable = "மாற்று மருந்து அருகில் கிடைக்கிறது",
    findNearbyStores = "அருகிலுள்ள கடைகளைத் தேடு",
    openInMaps = "வரைபடத்தில் காண்க",

    doctorReferralsTitle = "மருத்துவர் பரிந்துரை அமைப்பு",
    referToSpecialistTitle = "சிறப்பு மருத்துவருக்குப் பரிந்துரை",
    chooseSpecialty = "சிறப்புத் துறையைத் தேர்ந்தெடுக்கவும்",
    urgencyLevel = "அவசர நிலை",
    clinicalQuestionTitle = "குறிப்பிட்ட மருத்துவக் கேள்வி",
    reasonForReferral = "பரிந்துரைக்கான காரணம்",
    attachRecords = "முந்தைய அறிக்கைகளை இணைக்கவும்",
    acceptReferral = "பரிந்துரையை ஏற்றுக்கொள்",
    declineReferral = "பரிந்துரையை நிராகரி",
    requestMoreInfo = "கூடுதல் தகவல் கோரு",
    specialistFindingsTitle = "சிறப்பு மருத்துவர் பரிசோதனை முடிவுகள்",
    specialistRecommendationsTitle = "பரிந்துரைத்த மருத்துவருக்கு ஆலோசனை",
    submitSpecialistFindings = "முடிவுகளைச் சமர்ப்பி",
    referralSentSuccess = "பரிந்துரை அனுப்பப்பட்டது.",
    referralCompleted = "சிறப்பு ஆலோசனை நிறைவடைந்தது.",
    awaitingSpecialistReview = "சிறப்பு மருத்துவரின் ஆய்வுக்கு காத்திருக்கிறது",
    specialistAccepted = "சிறப்பு மருத்துவர் ஏற்றுக்கொண்டார்",
    specialistDeclined = "பரிந்துரை நிராகரிக்கப்பட்டது",

    selectLanguageTitle = "மொழியைத் தேர்ந்தெடுக்கவும் / Select Language",
    selectLanguageSubtitle = "பயன்பாட்டிற்கான உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்:",
    currentLanguageBadge = "தற்போதைய மொழி",
    applyLanguage = "பயன்படுத்து ✓",

    liveQueueTitle = "நேரலை மருத்துவமனை வரிசை",
    tokenNumber = "டோக்கன் #%d",
    callNextPatient = "அடுத்த நோயாளியை அழைக்கவும்",
    startConsultation = "ஆலோசனையைத் தொடங்கு",
    completeConsultation = "ஆலோசனையை முடி",
    noShow = "வராதவராகப் பதிவு செய்",
    skipPatient = "தவிர்",
    prioritizePatient = "முன்னுரிமை அளி",

    triageBreakdownTitle = "சிகிச்சை முன்னுரிமை பிரிவு",
    statTotal = "மொத்தம்",
    statPending = "நிலுவையில்",
    statResolved = "தீர்க்கப்பட்டது",
    statReferred = "பரிந்துரைக்கப்பட்டது",
    medicalHistoryTitle = "நோயாளியின் மருத்துவ வரலாறு",
    noMedicalHistory = "மருத்துவ வரலாறு எதுவும் பதிவு செய்யப்படவில்லை.",
    medicalHistoryTab = "மருத்துவ வரலாறு"
)

val MarathiStrings = AppStrings(
    appName = "VitalSense",
    tagline = "SehatSetu — ग्रामीण आरोग्य नेटवर्क",
    online = "ऑनलाइन",
    offline = "ऑफलाइन",
    exit = "बाहेर पडा",
    cancel = "रद्द करा",
    done = "पूर्ण",
    save = "जतन करा",
    submit = "सादर करा",
    urgent = "तातडीचे",
    active = "सक्रिय",
    highPriority = "उच्च प्राधान्य",
    highRisk = "अति धोका",
    moderateRisk = "मध्यम धोका",
    lowRisk = "कमी धोका / सामान्य",

    rolePatient = "रुग्ण",
    rolePatientDesc = "आरोग्य कार्ड व आपत्कालीन SOS",
    roleAsha = "आशा सेविका",
    roleAshaDesc = "गावातील रुग्ण नोंदी व मदत",
    roleDoctor = "डॉक्टर",
    roleDoctorDesc = "तपासणी व औषधोपचार",
    roleAdmin = "प्रशासक",
    roleAdminDesc = "जिल्हा आजार नियंत्रण",

    whoIsUsing = "अॅप कोण वापरत आहे?",
    selectRoleDesc = "आपल्या आरोग्य पोर्टलमध्ये जाण्यासाठी आपली भूमिका निवडा:",
    patientSignIn = "👤 रुग्ण लॉगिन",
    ashaSignIn = "🤝 आशा सेविका लॉगिन",
    doctorSignIn = "🩺 डॉक्टर क्लिनिकल पोर्टल",
    adminSignIn = "🛡️ जिल्हा आरोग्य प्रशासन",
    mobileNumber = "मोबाईल नंबर",
    ashaHelperIdOptional = "आशा मदतनीस आयडी (पर्यायी)",
    uniqueAshaId = "विशिष्ट आशा आयडी",
    securityPin = "४-अंकी सुरक्षा पिन",
    doctorEmail = "वैद्यकीय नोंदणी / ईमेल",
    password = "पासवर्ड",
    adminPasscode = "जिल्हा प्रशासन पासकोड",
    logInAsPatient = "रुग्ण म्हणून लॉगिन करा →",
    logInAsAsha = "आशा पोर्टलवर लॉगिन करा →",
    logInAsDoctor = "डॉक्टर पोर्टलवर लॉगिन करा →",
    logInAsAdmin = "जिल्हा आरोग्य नियंत्रण कक्षात जा →",
    quickDemoLogin = "⚡ झटपट १-टॅप डेमो लॉगिन:",
    offlineBanner = "📶 ऑफलाइन-फर्स्ट: इंटरनेट नसतानाही आरोग्य कार्ड सुरक्षितपणे काम करते",

    patientPortal = "रुग्ण आरोग्य पोर्टल",
    ashaPortal = "आशा सेविका कार्यक्षेत्र",
    doctorPortal = "क्लिनिकल तपासणी पोर्टल",
    adminPortal = "जिल्हा साथरोग नियंत्रण",
    actingAsProxy = "रुग्णाचे प्रतिनिधी म्हणून कार्यरत:",
    exitProxy = "प्रतिनिधी मोडमधून बाहेर पडा",

    namaste = "नमस्ते",
    village = "गाव",
    ashaAssigned = "आशा सेविका",
    patientGuideTitle = "आपले ग्रामीण आरोग्य पोर्टल",
    patientGuideMsg = "लक्षणे नोंदवण्यासाठी, औषधांची चिठ्ठी पाहण्यासाठी किंवा आपल्या आशा सेविकेशी संपर्क साधण्यासाठी खाली टॅप करा.",
    offlineHealthCard = "ऑफलाइन आरोग्य कार्ड",
    viewCard = "कार्ड पहा →",
    activeCondition = "सध्याची आरोग्य स्थिती:",
    nextCheckup = "पुढील तपासणी:",
    noneScheduled = "नियोजित नाही",
    cachedOffline = "ऑफलाइन सुरक्षित ✓",
    howCanWeHelp = "आम्ही आज आपल्याला कशी मदत करू शकतो?",
    tapServiceDesc = "तपासणी किंवा सल्ला मिळवण्यासाठी सेवा निवडा:",
    myPrescriptions = "💊 माझी औषध प्रिस्क्रिप्शन",
    uploadRx = "➕ नवीन प्रिस्क्रिप्शन",
    noPrescriptions = "अद्याप कोणतीही औषध नोंद नाही",
    scanOrWrite = "चिठ्ठी स्कॅन करा किंवा लिहून ठेवा",
    districtAdvisories = "📢 जिल्हा आरोग्य सूचना",
    issuedBy = "जारीकर्ते:",
    emergencySos = "आपत्कालीन SOS",
    emergencySosDesc = "आशा सेविका व १०८ रुग्णवाहिकेला तात्काळ अलर्ट",
    trigger = "अलर्ट पाठवा",
    confirmSosTitle = "आपत्कालीन SOS पाठवायचा आहे का?",
    confirmSosMsg = "हे तात्काळ आपल्या आशा सेविकेला आणि प्राथमिक आरोग्य केंद्राला आपल्या माहितीसह अलर्ट पाठवेल.",
    yesSendAlert = "🚨 होय, आपत्कालीन अलर्ट पाठवा",
    sosDispatchedTitle = "आपत्कालीन अलर्ट पाठवला गेला!",
    sosDispatchedMsg = "आशा सेविका व आपत्कालीन पथकाला माहिती दिली आहे. कृपया शांत रहा.",
    zeroInternetFallbacks = "इंटरनेट नसतानाचे तात्काळ पर्याय:",
    smsAsha = "📱 आशा सेविकेला थेट SMS पाठवा",
    call108 = "📞 १०८ रुग्णवाहिकेला कॉल करा",

    catGeneralMedicine = "सामान्य औषधोपचार",
    catMaternalHealth = "मातृ व बाळ आरोग्य",
    catFitness = "शारीरिक व्यायाम",
    catNutrition = "आहार व पोषण",
    catMentalHealth = "मानसिक आरोग्य",
    catEmergency = "आपत्कालीन मदत",

    assignedVillages = "नेमून दिलेली गावे:",
    uniqueAshaCardTitle = "आपले विशिष्ट आशा ओळखपत्र",
    shareAshaIdDesc = "गावातील रुग्णांना थेट जोडण्यासाठी हा ८-अक्षरी कोड किंवा QR शेअर करा.",
    newPatient = "➕ नवीन रुग्ण",
    sendNotice = "📢 नोटीस पाठवा",
    villageCaseload = "गावातील रुग्ण नोंदणी",
    noPatientsYet = "अद्याप कोणतेही रुग्ण नोंदवलेले नाहीत.",
    scanRx = "प्रिस्क्रिप्शन स्कॅन",
    proxyMode = "प्रतिनिधी मोड",
    emergencyPatientAlerts = "🚨 आपत्कालीन रुग्ण अलर्ट",
    sosAlertForPatient = "रुग्णासाठी आपत्कालीन SOS पाठवायचा का?",
    confirmSosPatientMsg = "हे जिल्हा आपत्कालीन रांगेत रुग्णाला अतिगंभीर श्रेणीत नोंदवेल.",
    sosDispatchedForPatient = "🚨 रुग्णासाठी आपत्कालीन अलर्ट पाठवला गेला.",
    sosFailedForPatient = "अलर्ट पाठवता आला नाही. कृपया थेट १०८ वर कॉल करा.",
    retry = "पुन्हा प्रयत्न करा",

    pendingCases = "तपासणीसाठी प्रलंबित रुग्ण",
    criticalCases = "अतिगंभीर / तातडीचे रुग्ण",
    scheduledAppts = "आजच्या भेटी",
    activeInQueue = "रांगेतील सक्रिय रुग्ण",
    specialistQueue = "तज्ज्ञ डॉक्टर रांग",
    noPendingCases = "सध्या कोणतेही प्रलंबित रुग्ण नाहीत!",
    symptoms = "लक्षणे",
    review = "रुग्ण तपासा →",
    history = "वैद्यकीय इतिहास",
    upcomingConsultations = "आगामी सल्लामसलत",
    proposeAppt = "वेळ निश्चित करा",
    dispensaryStock = "औषध साठा",
    lowStock = "कमी साठा अलर्ट",
    patientDirectory = "रुग्ण यादी",
    searchPatient = "रुग्ण शोधा",
    searchPlaceholder = "नाव किंवा आयडी टाका...",
    caseQueue = "रुग्ण रांग",
    reportedSymptoms = "नोंदवलेली लक्षणे व माहिती",
    doctorAdviceTitle = "डॉक्टरांचा सल्ला",
    quickTemplates = "झटपट वैद्यकीय सल्ले",
    issueRx = "💊 औषध चिठ्ठी द्या",
    refer = "🩺 तज्ज्ञांकडे पाठवा",
    submitAdvice = "सल्ला नोंदवा",
    updateAdvice = "सल्ला अद्यतनित करा",

    districtCommand = "जिल्हा आरोग्य नियंत्रण कक्ष",
    surveillanceRegion = "निगरानी क्षेत्र: बागेश्वर जिल्हा",
    totalActiveCases = "एकूण सक्रिय रुग्ण",
    monitoredVillages = "निगराणीखालील गावे",
    outbreakSurveillance = "साथरोग नकाशा",
    liveTelemetry = "थेट आरोग्य आकडेवारी",
    broadcastAlertBtn = "📢 आरोग्य सूचना जारी करा",
    dispatchedDirectives = "जारी केलेल्या मार्गदर्शक सूचना",
    dispensaryInventory = "औषध साठा व मागणी",

    uploadPrescriptionTitle = "डॉक्टरांची चिठ्ठी डिजिटल करा",
    cameraAiScan = "📷 कॅमेरा / AI स्कॅन",
    writeDown = "✍️ लिहून काढा",
    onDeviceAiBadge = "⚡ AI स्कॅनर: इंटरनेट नसतानाही कागदी चिठ्ठी वाचतो.",
    selectDocSample = "कागदपत्राचा नमुना निवडा:",
    extractedRawText = "स्कॅन केलेला मजकूर:",
    parsedMedicines = "ओळखलेली औषधे",
    saveDigitizedRx = "डिजिटल चिठ्ठी जतन करा ✓",
    addMedicine = "➕ औषध जोडा:",
    medicineName = "औषधाचे नाव",
    dosage = "मात्रा (Dosage)",
    duration = "कालावधी",
    frequency = "कधी घ्यावे",
    savePrescriptionRecord = "औषध नोंद जतन करा ✓",

    callRinging = "घंटी वाजत आहे...",
    callConnecting = "कॉल जोडला जात आहे...",
    callOngoing = "कॉल सुरू आहे",
    callEnded = "कॉल समाप्त",
    endCall = "कॉल संपवा",
    mute = "माइक बंद",
    unmute = "माइक चालू",
    speaker = "स्पीकर",
    videoCall = "व्हिडिओ कॉल",
    voiceCall = "ऑडिओ कॉल",
    emergencyDoctorCall = "🚨 आपत्कालीन डॉक्टर कॉल",
    routineConsultCall = "🩺 नियमित सल्लामसलत कॉल",
    autoEscalatingInSeconds = "%d सेकंदात पुढील डॉक्टरांना कॉल जोडला जाईल",
    emergencyDoctorOnCall = "ड्युटीवरील आपत्कालीन डॉक्टर",

    medicineAvailabilityTitle = "औषधांची उपलब्धता व पर्याय",
    nearbyPharmaciesTitle = "जवळची औषध दुकाने व फार्मसी",
    inStock = "उपलब्ध आहे",
    outOfStock = "साठ्यात नाही",
    limitedStock = "मर्यादित साठा",
    alternativesAvailable = "समान घटकांचे पर्यायी औषध जवळ उपलब्ध",
    findNearbyStores = "जवळची दुकाने शोधा",
    openInMaps = "नकाशात पहा",

    doctorReferralsTitle = "डॉक्टर-टू-डॉक्टर तज्ज्ञ रेफरल",
    referToSpecialistTitle = "तज्ज्ञ डॉक्टरांकडे पाठवा",
    chooseSpecialty = "तज्ज्ञ विभाग निवडा",
    urgencyLevel = "तातडीची पातळी",
    clinicalQuestionTitle = "वैद्यकीय विचारणा / प्रश्न",
    reasonForReferral = "रेफर करण्याचे कारण",
    attachRecords = "मागील तपासण्या व अहवाल जोडा",
    acceptReferral = "रेफरल स्वीकारा",
    declineReferral = "रेफरल नाकारा",
    requestMoreInfo = "अधिक माहिती मागा",
    specialistFindingsTitle = "तज्ज्ञ तपासणी निष्कर्ष",
    specialistRecommendationsTitle = "रेफर करणाऱ्या डॉक्टरांसाठी सल्ला",
    submitSpecialistFindings = "अंतिम निष्कर्ष सादर करा",
    referralSentSuccess = "रेफरल तज्ज्ञांकडे पाठवले गेले.",
    referralCompleted = "तज्ज्ञ तपासणी पूर्ण झाली.",
    awaitingSpecialistReview = "तज्ज्ञ डॉक्टरांच्या अभिप्रायाची प्रतीक्षा आहे",
    specialistAccepted = "तज्ज्ञ डॉक्टरांनी तपासणी स्वीकारली",
    specialistDeclined = "रेफरल नाकारले गेले",

    selectLanguageTitle = "भाषा निवडा / Select Language",
    selectLanguageSubtitle = "संपूर्ण अॅपसाठी आपली पसंतीची भाषा निवडा:",
    currentLanguageBadge = "सक्रिय भाषा",
    applyLanguage = "लागू करा ✓",

    liveQueueTitle = "थेट रुग्णालय रांग",
    tokenNumber = "टोकन #%d",
    callNextPatient = "पुढील रुग्णाला बोलवा",
    startConsultation = "तपासणी सुरू करा",
    completeConsultation = "तपासणी पूर्ण करा",
    noShow = "गैरहजर नोंदवा",
    skipPatient = "पुढे जा",
    prioritizePatient = "प्राधान्य द्या",

    triageBreakdownTitle = "ट्रायज तीव्रता विश्लेषण",
    statTotal = "एकूण",
    statPending = "प्रलंबित",
    statResolved = "निराकरण",
    statReferred = "रेफर केले",
    medicalHistoryTitle = "रुग्णाचा संपूर्ण वैद्यकीय इतिहास",
    noMedicalHistory = "कोणताही वैद्यकीय इतिहास नोंदवलेला नाही.",
    medicalHistoryTab = "वैद्यकीय इतिहास"
)

val LocalAppStrings = staticCompositionLocalOf { EnglishStrings }

object AppLanguageManager {
    fun getStrings(language: AppLanguage): AppStrings {
        return when (language) {
            AppLanguage.ENGLISH -> EnglishStrings
            AppLanguage.HINDI -> HindiStrings
            AppLanguage.TAMIL -> TamilStrings
            AppLanguage.MARATHI -> MarathiStrings
        }
    }
}
