package com.vitalsense.app.core.ui.theme

import androidx.compose.runtime.Composable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.runtime.staticCompositionLocalOf

enum class AppLanguage(val code: String, val displayName: String, val buttonLabel: String) {
    ENGLISH("en", "English", "हिंदी"),
    HINDI("hi", "हिंदी (Hindi)", "English")
}

data class AppStrings(
    val appName: String,
    val tagline: String,
    val online: String,
    val offline: String,
    val exit: String,
    val cancel: String,
    val done: String,
    val save: String,
    val submit: String,
    val urgent: String,
    val active: String,
    val highPriority: String,
    val highRisk: String,
    val moderateRisk: String,
    val lowRisk: String,

    // Roles
    val rolePatient: String,
    val rolePatientDesc: String,
    val roleAsha: String,
    val roleAshaDesc: String,
    val roleDoctor: String,
    val roleDoctorDesc: String,
    val roleAdmin: String,
    val roleAdminDesc: String,

    // Login Screen
    val whoIsUsing: String,
    val selectRoleDesc: String,
    val patientSignIn: String,
    val ashaSignIn: String,
    val doctorSignIn: String,
    val adminSignIn: String,
    val mobileNumber: String,
    val ashaHelperIdOptional: String,
    val uniqueAshaId: String,
    val securityPin: String,
    val doctorEmail: String,
    val password: String,
    val adminPasscode: String,
    val logInAsPatient: String,
    val logInAsAsha: String,
    val logInAsDoctor: String,
    val logInAsAdmin: String,
    val quickDemoLogin: String,
    val offlineBanner: String,

    // Top Bar
    val patientPortal: String,
    val ashaPortal: String,
    val doctorPortal: String,
    val adminPortal: String,
    val actingAsProxy: String,
    val exitProxy: String,

    // Patient Home
    val namaste: String,
    val village: String,
    val ashaAssigned: String,
    val patientGuideTitle: String,
    val patientGuideMsg: String,
    val offlineHealthCard: String,
    val viewCard: String,
    val activeCondition: String,
    val nextCheckup: String,
    val noneScheduled: String,
    val cachedOffline: String,
    val howCanWeHelp: String,
    val tapServiceDesc: String,
    val myPrescriptions: String,
    val uploadRx: String,
    val noPrescriptions: String,
    val scanOrWrite: String,
    val districtAdvisories: String,
    val issuedBy: String,
    val emergencySos: String,
    val emergencySosDesc: String,
    val trigger: String,
    val confirmSosTitle: String,
    val confirmSosMsg: String,
    val yesSendAlert: String,
    val sosDispatchedTitle: String,
    val sosDispatchedMsg: String,
    val zeroInternetFallbacks: String,
    val smsAsha: String,
    val call108: String,

    // Categories
    val catGeneralMedicine: String,
    val catMaternalHealth: String,
    val catFitness: String,
    val catNutrition: String,
    val catMentalHealth: String,
    val catEmergency: String,

    // ASHA Home
    val assignedVillages: String,
    val uniqueAshaCardTitle: String,
    val shareAshaIdDesc: String,
    val newPatient: String,
    val sendNotice: String,
    val villageCaseload: String,
    val noPatientsYet: String,
    val scanRx: String,
    val proxyMode: String,
    val emergencyPatientAlerts: String,

    // Doctor Home & Case Detail
    val pendingCases: String,
    val criticalCases: String,
    val scheduledAppts: String,
    val activeInQueue: String,
    val specialistQueue: String,
    val noPendingCases: String,
    val symptoms: String,
    val review: String,
    val history: String,
    val upcomingConsultations: String,
    val proposeAppt: String,
    val dispensaryStock: String,
    val lowStock: String,
    val patientDirectory: String,
    val searchPatient: String,
    val searchPlaceholder: String,
    val caseQueue: String,
    val reportedSymptoms: String,
    val doctorAdviceTitle: String,
    val quickTemplates: String,
    val issueRx: String,
    val refer: String,
    val submitAdvice: String,
    val updateAdvice: String,

    // Admin Home
    val districtCommand: String,
    val surveillanceRegion: String,
    val totalActiveCases: String,
    val monitoredVillages: String,
    val outbreakSurveillance: String,
    val liveTelemetry: String,
    val broadcastAlertBtn: String,
    val dispatchedDirectives: String,
    val dispensaryInventory: String,

    // Prescription & OCR
    val uploadPrescriptionTitle: String,
    val cameraAiScan: String,
    val writeDown: String,
    val onDeviceAiBadge: String,
    val selectDocSample: String,
    val extractedRawText: String,
    val parsedMedicines: String,
    val saveDigitizedRx: String,
    val addMedicine: String,
    val medicineName: String,
    val dosage: String,
    val duration: String,
    val frequency: String,
    val savePrescriptionRecord: String
)

val EnglishStrings = AppStrings(
    appName = "VitalSense",
    tagline = "SehatSetu — Rural Health Bridge",
    online = "Online",
    offline = "Offline",
    exit = "Exit",
    cancel = "Cancel",
    done = "Done",
    save = "Save",
    submit = "Submit",
    urgent = "URGENT",
    active = "ACTIVE",
    highPriority = "HIGH PRIORITY",
    highRisk = "High Risk",
    moderateRisk = "Moderate Risk",
    lowRisk = "Low Risk",

    rolePatient = "Patient",
    rolePatientDesc = "Health card & SOS",
    roleAsha = "ASHA Worker",
    roleAshaDesc = "Caseload & Proxy",
    roleDoctor = "Doctor",
    roleDoctorDesc = "Review & Prescribe",
    roleAdmin = "Admin",
    roleAdminDesc = "Outbreak Trends",

    whoIsUsing = "Who is using the app?",
    selectRoleDesc = "Select your role to access your dedicated healthcare portal:",
    patientSignIn = "👤 Patient Sign-In",
    ashaSignIn = "🤝 ASHA Worker Sign-In",
    doctorSignIn = "🩺 Doctor Clinical Portal",
    adminSignIn = "🛡️ District Health Admin",
    mobileNumber = "Mobile Number",
    ashaHelperIdOptional = "ASHA Helper ID (Optional)",
    uniqueAshaId = "Unique ASHA ID",
    securityPin = "4-Digit Security PIN",
    doctorEmail = "Medical Registration / Email",
    password = "Password",
    adminPasscode = "District Admin Passcode",
    logInAsPatient = "Log In as Patient →",
    logInAsAsha = "Log In to ASHA Caseload →",
    logInAsDoctor = "Log In to Clinical Portal →",
    logInAsAdmin = "Enter District Health Command →",
    quickDemoLogin = "⚡ Quick 1-Tap Demo Login:",
    offlineBanner = "📶 Offline-First: Health Card & Core Tools Work With Zero Internet",

    patientPortal = "Patient Portal",
    ashaPortal = "ASHA Worker Caseload",
    doctorPortal = "Clinical Review Portal",
    adminPortal = "District Outbreak Command",
    actingAsProxy = "Acting as Proxy for Patient:",
    exitProxy = "Exit Proxy",

    namaste = "Namaste",
    village = "Village",
    ashaAssigned = "ASHA",
    patientGuideTitle = "Your Rural Health Portal",
    patientGuideMsg = "Tap any health category below to log symptoms, check prescriptions, or connect with your ASHA helper.",
    offlineHealthCard = "OFFLINE HEALTH CARD",
    viewCard = "View Card →",
    activeCondition = "Active Condition:",
    nextCheckup = "Next Checkup:",
    noneScheduled = "None Scheduled",
    cachedOffline = "Cached Offline ✓",
    howCanWeHelp = "How can we help you today?",
    tapServiceDesc = "Tap a service to report health condition or consult a doctor:",
    myPrescriptions = "💊 My Prescriptions",
    uploadRx = "➕ Upload Rx",
    noPrescriptions = "No prescriptions recorded yet",
    scanOrWrite = "Scan paper slip or write down medicines",
    districtAdvisories = "📢 District Health Advisories",
    issuedBy = "Issued by:",
    emergencySos = "EMERGENCY SOS",
    emergencySosDesc = "Alert ASHA & Doctor (Works via SMS)",
    trigger = "TRIGGER",
    confirmSosTitle = "Confirm Emergency SOS",
    confirmSosMsg = "This will immediately send an Emergency SOS alert with your location to:",
    yesSendAlert = "Yes, Send Emergency Alert",
    sosDispatchedTitle = "Emergency SOS Dispatched",
    sosDispatchedMsg = "Emergency broadcast sent with your location to ASHA and health monitoring.",
    zeroInternetFallbacks = "Zero Internet Fallbacks:",
    smsAsha = "💬 SMS ASHA",
    call108 = "📞 Call 108",

    catGeneralMedicine = "General Medicine",
    catMaternalHealth = "Maternal Health",
    catFitness = "Fitness & Physical",
    catNutrition = "Nutrition & Diet",
    catMentalHealth = "Mental Wellness",
    catEmergency = "Emergency Help",

    assignedVillages = "Assigned Villages:",
    uniqueAshaCardTitle = "UNIQUE ASHA HELPER ID",
    shareAshaIdDesc = "Share this ID with patients to link you as helper",
    newPatient = "+ New Patient",
    sendNotice = "📢 Send Notice",
    villageCaseload = "Village Caseload",
    noPatientsYet = "No patients registered yet in this village.",
    scanRx = "📷 Scan Rx",
    proxyMode = "🤝 Proxy Mode",
    emergencyPatientAlerts = "🚨 Emergency Patient SOS Alerts",

    pendingCases = "Pending",
    criticalCases = "Critical Cases",
    scheduledAppts = "Appointments",
    activeInQueue = "Active in Queue",
    specialistQueue = "Specialist Triage Queue",
    noPendingCases = "No pending patient cases in your triage queue.",
    symptoms = "Symptoms:",
    review = "Review →",
    history = "📋 History",
    upcomingConsultations = "Scheduled Appointments",
    proposeAppt = "➕ Propose Appt",
    dispensaryStock = "Dispensary Stock Check",
    lowStock = "LOW STOCK",
    patientDirectory = "🔍 Patient Records Directory",
    searchPatient = "Search Patient",
    searchPlaceholder = "Search by name or village...",
    caseQueue = "Case Queue",
    reportedSymptoms = "Reported Symptoms & Notes:",
    doctorAdviceTitle = "Clinical Response & Advice",
    quickTemplates = "Quick Template Responses:",
    issueRx = "💊 Issue Rx",
    refer = "↗ Refer",
    submitAdvice = "Submit Medical Advice ✓",
    updateAdvice = "Update Clinical Response ✓",

    districtCommand = "District Health Command",
    surveillanceRegion = "Surveillance Region: Rampur District, UP",
    totalActiveCases = "Total Active Cases",
    monitoredVillages = "Monitored Villages",
    outbreakSurveillance = "🗺️ Outbreak Surveillance",
    liveTelemetry = "Live Telemetry Refresh",
    broadcastAlertBtn = "📢 Broadcast Health Directive / Alert",
    dispatchedDirectives = "📋 Dispatched Directives",
    dispensaryInventory = "🏥 District Dispensary Inventory",

    uploadPrescriptionTitle = "Upload Prescription",
    cameraAiScan = "📷 Camera / AI Scan",
    writeDown = "✍️ Write Down",
    onDeviceAiBadge = "⚡ On-Device AI: Scans doctor slips offline with zero internet.",
    selectDocSample = "Select Document Sample:",
    extractedRawText = "Extracted Raw Text:",
    parsedMedicines = "Parsed Medicines",
    saveDigitizedRx = "Save Digitized Prescription ✓",
    addMedicine = "➕ Add Prescribed Medicine:",
    medicineName = "Medicine Name",
    dosage = "Dosage",
    duration = "Duration",
    frequency = "Frequency / Timing",
    savePrescriptionRecord = "Save Prescription Record ✓"
)

val HindiStrings = AppStrings(
    appName = "VitalSense",
    tagline = "सेहतसेतु — ग्रामीण स्वास्थ्य सेतु",
    online = "ऑनलाइन",
    offline = "ऑफ़लाइन",
    exit = "बाहर निकलें",
    cancel = "रद्द करें",
    done = "पूर्ण",
    save = "सहेजें",
    submit = "जमा करें",
    urgent = "अति आवश्यक",
    active = "सक्रिय",
    highPriority = "उच्च प्राथमिकता",
    highRisk = "उच्च जोखिम",
    moderateRisk = "मध्यम जोखिम",
    lowRisk = "सामान्य",

    rolePatient = "मरीज़",
    rolePatientDesc = "स्वास्थ्य कार्ड और आपातकालीन सेवा",
    roleAsha = "आशा कार्यकर्ता",
    roleAshaDesc = "केस सूची और प्रॉक्सी सेवा",
    roleDoctor = "डॉक्टर",
    roleDoctorDesc = "समीक्षा और नुस्खे",
    roleAdmin = "प्रशासक",
    roleAdminDesc = "रोग प्रकोप निगरानी",

    whoIsUsing = "ऐप का उपयोग कौन कर रहा है?",
    selectRoleDesc = "अपने स्वास्थ्य पोर्टल तक पहुँचने के लिए अपनी भूमिका चुनें:",
    patientSignIn = "👤 मरीज़ लॉगिन",
    ashaSignIn = "🤝 आशा कार्यकर्ता लॉगिन",
    doctorSignIn = "🩺 डॉक्टर क्लिनिकल पोर्टल",
    adminSignIn = "🛡️ जिला स्वास्थ्य प्रशासन",
    mobileNumber = "मोबाइल नंबर",
    ashaHelperIdOptional = "आशा हेल्पर आईडी (वैकल्पिक)",
    uniqueAshaId = "यूनिक आशा आईडी",
    securityPin = "4-अंकों का सुरक्षा पिन",
    doctorEmail = "मेडिकल पंजीकरण / ईमेल",
    password = "पासवर्ड",
    adminPasscode = "जिला एडमिन पासकोड",
    logInAsPatient = "मरीज़ के रूप में लॉगिन करें →",
    logInAsAsha = "आशा केसलोड में लॉगिन करें →",
    logInAsDoctor = "क्लिनिकल पोर्टल में लॉगिन करें →",
    logInAsAdmin = "जिला स्वास्थ्य कमान में प्रवेश करें →",
    quickDemoLogin = "⚡ त्वरित 1-टैप डेमो लॉगिन:",
    offlineBanner = "📶 ऑफ़लाइन-फर्स्ट: स्वास्थ्य कार्ड और मुख्य उपकरण बिना इंटरनेट के काम करते हैं",

    patientPortal = "मरीज़ पोर्टल",
    ashaPortal = "आशा कार्यकर्ता केसलोड",
    doctorPortal = "क्लिनिकल समीक्षा पोर्टल",
    adminPortal = "जिला प्रकोप निगरानी केंद्र",
    actingAsProxy = "मरीज़ के लिए प्रॉक्सी के रूप में कार्यरत:",
    exitProxy = "प्रॉक्सी छोड़ें",

    namaste = "नमस्ते",
    village = "गाँव",
    ashaAssigned = "आशा सहायिका",
    patientGuideTitle = "आपका ग्रामीण स्वास्थ्य पोर्टल",
    patientGuideMsg = "लक्षण दर्ज करने, नुस्खे देखने या आशा सहायिका से जुड़ने के लिए नीचे किसी भी श्रेणी पर टैप करें।",
    offlineHealthCard = "ऑफ़लाइन स्वास्थ्य कार्ड",
    viewCard = "कार्ड देखें →",
    activeCondition = "वर्तमान स्थिति:",
    nextCheckup = "अगली जांच:",
    noneScheduled = "कोई निर्धारित नहीं",
    cachedOffline = "ऑफ़लाइन सुरक्षित ✓",
    howCanWeHelp = "आज हम आपकी क्या मदद कर सकते हैं?",
    tapServiceDesc = "स्वास्थ्य समस्या दर्ज करने या डॉक्टर से परामर्श के लिए टैप करें:",
    myPrescriptions = "💊 मेरे नुस्खे (दवाइयाँ)",
    uploadRx = "➕ नुस्खा अपलोड",
    noPrescriptions = "अभी तक कोई नुस्खा दर्ज नहीं है",
    scanOrWrite = "कागज़ की पर्ची स्कैन करें या दवाइयाँ लिखें",
    districtAdvisories = "📢 जिला स्वास्थ्य सलाह",
    issuedBy = "द्वारा जारी:",
    emergencySos = "आपातकालीन एसओएस (SOS)",
    emergencySosDesc = "आशा और डॉक्टर को सूचित करें (SMS द्वारा)",
    trigger = "भेजें",
    confirmSosTitle = "आपातकालीन अलर्ट की पुष्टि करें",
    confirmSosMsg = "यह तुरंत आपके स्थान के साथ आपातकालीन अलर्ट भेजेगा:",
    yesSendAlert = "हाँ, आपातकालीन अलर्ट भेजें",
    sosDispatchedTitle = "आपातकालीन अलर्ट भेजा गया",
    sosDispatchedMsg = "आपके स्थान के साथ आपातकालीन संदेश आशा सहायिका और स्वास्थ्य केंद्र को भेज दिया गया है।",
    zeroInternetFallbacks = "बिना इंटरनेट के विकल्प:",
    smsAsha = "💬 आशा को SMS",
    call108 = "📞 108 पर कॉल",

    catGeneralMedicine = "सामान्य चिकित्सा",
    catMaternalHealth = "मातृ एवं शिशु स्वास्थ्य",
    catFitness = "शारीरिक स्वास्थ्य",
    catNutrition = "पोषण एवं आहार",
    catMentalHealth = "मानसिक स्वास्थ्य",
    catEmergency = "आपातकालीन सेवा",

    assignedVillages = "आवंटित गाँव:",
    uniqueAshaCardTitle = "यूनिक आशा हेल्पर आईडी",
    shareAshaIdDesc = "मरीज़ों को जोड़ने के लिए यह आईडी साझा करें",
    newPatient = "+ नया मरीज़",
    sendNotice = "📢 सूचना भेजें",
    villageCaseload = "गाँव के मरीज़ों की सूची",
    noPatientsYet = "इस गाँव में अभी तक कोई मरीज़ पंजीकृत नहीं है।",
    scanRx = "📷 पर्ची स्कैन",
    proxyMode = "🤝 प्रॉक्सी मोड",
    emergencyPatientAlerts = "🚨 आपातकालीन मरीज़ अलर्ट",

    pendingCases = "लंबित मामले",
    criticalCases = "गंभीर मामले",
    scheduledAppts = "अपॉइंटमेंट",
    activeInQueue = "कतार में सक्रिय",
    specialistQueue = "विशेषज्ञ केस कतार",
    noPendingCases = "आपकी कतार में कोई लंबित मामला नहीं है।",
    symptoms = "लक्षण:",
    review = "समीक्षा करें →",
    history = "📋 इतिहास",
    upcomingConsultations = "निर्धारित अपॉइंटमेंट",
    proposeAppt = "➕ अपॉइंटमेंट तय करें",
    dispensaryStock = "दवाखाना स्टॉक जांच",
    lowStock = "कम स्टॉक",
    patientDirectory = "🔍 मरीज़ रिकॉर्ड निर्देशिका",
    searchPatient = "मरीज़ खोजें",
    searchPlaceholder = "नाम या गाँव से खोजें...",
    caseQueue = "केस सूची",
    reportedSymptoms = "दर्ज लक्षण एवं नोट्स:",
    doctorAdviceTitle = "चिकित्सक की सलाह एवं उपचार",
    quickTemplates = "त्वरित प्रतिक्रिया विकल्प:",
    issueRx = "💊 नुस्खा दें",
    refer = "↗ रेफर करें",
    submitAdvice = "चिकित्सा सलाह सबमिट करें ✓",
    updateAdvice = "चिकित्सा सलाह अपडेट करें ✓",

    districtCommand = "जिला स्वास्थ्य कमान केंद्र",
    surveillanceRegion = "निगरानी क्षेत्र: रामपुर जिला, उत्तर प्रदेश",
    totalActiveCases = "कुल सक्रिय मामले",
    monitoredVillages = "निगरानी वाले गाँव",
    outbreakSurveillance = "🗺️ रोग प्रकोप निगरानी",
    liveTelemetry = "लाइव डेटा रिफ्रेश",
    broadcastAlertBtn = "📢 स्वास्थ्य निर्देश / अलर्ट प्रसारित करें",
    dispatchedDirectives = "📋 जारी किए गए निर्देश",
    dispensaryInventory = "🏥 जिला दवाखाना स्टॉक",

    uploadPrescriptionTitle = "नुस्खा अपलोड करें",
    cameraAiScan = "📷 कैमरा / AI स्कैन",
    writeDown = "✍️ हाथ से लिखें",
    onDeviceAiBadge = "⚡ ऑन-डिवाइस AI: बिना इंटरनेट के डॉक्टर की पर्ची स्कैन करता है।",
    selectDocSample = "दस्तावेज़ का नमूना चुनें:",
    extractedRawText = "स्कैन किया गया टेक्स्ट:",
    parsedMedicines = "पहचानी गई दवाइयाँ",
    saveDigitizedRx = "डिजिटल नुस्खा सहेजें ✓",
    addMedicine = "➕ निर्धारित दवा जोड़ें:",
    medicineName = "दवा का नाम",
    dosage = "खुराक (Dosage)",
    duration = "अवधि (Duration)",
    frequency = "समय / कब लें",
    savePrescriptionRecord = "नुस्खा रिकॉर्ड सहेजें ✓"
)

val LocalAppStrings = staticCompositionLocalOf { EnglishStrings }

object AppLanguageManager {
    fun getStrings(language: AppLanguage): AppStrings {
        return when (language) {
            AppLanguage.ENGLISH -> EnglishStrings
            AppLanguage.HINDI -> HindiStrings
        }
    }
}
